/*
 * Order API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using OrderService.Contracts.Attributes;
using OrderService.Contracts.Models;

namespace OrderService.Contracts.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class OrdersApiController : ControllerBase
    { 
        /// <summary>
        /// Get an order by id
        /// </summary>
        /// <param name="orderId">Id of the order to get</param>
        /// <response code="200">Order</response>
        [HttpGet]
        [Route("/api/orders/{orderId}")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Order))]
        public abstract Task<IActionResult> GetOrderById([FromRoute (Name = "orderId")][Required]Guid orderId);

        /// <summary>
        /// Get all orders
        /// </summary>
        /// <response code="200">Orders</response>
        [HttpGet]
        [Route("/api/orders")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<Order>))]
        public abstract Task<IActionResult> GetOrders();

        /// <summary>
        /// Create an order
        /// </summary>
        /// <param name="order"></param>
        /// <response code="200">Created order</response>
        [HttpPost]
        [Route("/api/orders")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Order))]
        public abstract Task<IActionResult> PostOrder([FromBody]Order order);

        /// <summary>
        /// Update an order by id
        /// </summary>
        /// <param name="orderId">Id of the order to update</param>
        /// <response code="200">Updated order</response>
        [HttpPut]
        [Route("/api/orders/{orderId}")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Order))]
        public abstract Task<IActionResult> UpdateOrderById([FromRoute (Name = "orderId")][Required]Guid orderId);
    }
}
